---
apiVersion: v1 
kind: ConfigMap
metadata:
  name: sql-config
data:
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  MYSQL_DATABASE: "cities"
---
apiVersion: v1 
kind: Secret
metadata:
  name: sql-secret
type: Opaque
data:
  MYSQL_USER: c2hpcHBpbmc=
  MYSQL_PASSWORD: c2VjcmV0
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sql-set 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        pod: mysql-pod
        tier: db
    spec:
      containers:
      - name: mysql-cntr
        image: udaysha10/mysql:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: sql-config
        - secretRef:
            name: sql-secret
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: sql-pvc
          mountPath: /var/lib/mysql
  serviceName: mysql
  selector:
    matchLabels:
      pod: mysql-pod
      tier: db
  volumeClaimTemplates:
  - metadata:
      name: sql-pvc
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1 
kind: Service
metadata:
  name: mysql
spec:
  selector:
   pod: mysql-pod
   tier: db 
  ports:
   - protocol: TCP
     port: 3306
     targetPort: 3306
  clusterIP: None
---
