apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: spot2-cluster
  region: us-east-1

managedNodeGroups:

# `instanceTypes` defaults to [`m5.large`]
- name: spot-1
  spot: false
  desiredCapacity: 1
  instanceType: t2.medium
  ssh:
    publicKeyName: k8s
