---
apiVersion: v1 
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
    type: mongo-service
spec:
  clusterIP: None  # headless service will get all ips of replicas each time
  selector:
    app: mongodb
    type: mongo-service
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
 spec: # define pods template here
  template:
    metadata:
      name: mongodb-pod
      labels: # pod labels
        app: mongodb-pod
        tier: db        
    spec:
      containers:
      - name: mongodb
        image: udaysha10/mongodb:k8
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-pvc
          mountPath: /data/db
  replicas: 3
  selector:
    matchLabels:
      app: mongodb-pod
      tier: db
  serviceName: mongodb
  minReadySeconds: 10
  # strategy:
  #   type: rollingUpdate
  #   rollingUpdate:
  #     maxUnavailable: 1
  #     maxSurge: 1
  volumeClaimTemplates:
  - metadata:
      name: mongo-pvc
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 6Gi
---